version: "3.7"

x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:

  server:
    image: "${SERVER_IMAGE}"
    volumes:
      - ./grai-server/app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=grai
      - DB_USER=grai
      - DB_PASSWORD=grai
      - DJANGO_SUPERUSER_USERNAME=null@grai.io
      - DJANGO_SUPERUSER_PASSWORD=super_secret
      - DJANGO_SUPERUSER_WORKSPACE=Workspace1
      - SERVER_HOST=localhost
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    entrypoint: /bin/sh
    command:
         - "-c"
         - "FRONTEND_URL=$$UFFIZZI_URL/ /usr/src/app/entrypoint.sh gunicorn the_guide.wsgi -b 127.0.0.1:8000 -w 2"
    deploy:
          resources:
            limits:
              memory: 2000M  
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=grai
      - POSTGRES_PASSWORD=grai
      - POSTGRES_DB=grai
    ports:
      - 5432:5432
    deploy:
          resources:
            limits:
              memory: 500M    
  
  frontend:
    image: "${FRONTEND_IMAGE}"
    entrypoint: /bin/sh
    command:
         - "-c"
         - "REACT_APP_SERVER_URL=$$UFFIZZI_URL/api /usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""
    deploy:
          resources:
            limits:
              memory: 2000M 
  
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"             
              
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx-uffizzi:/etc/nginx
      
  celery_worker:
    image: "${SERVER_IMAGE}"
    volumes:
      - ./grai-server/app/:/usr/src/app/
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=grai
      - DB_USER=grai
      - DB_PASSWORD=grai
      - DJANGO_SUPERUSER_USERNAME=null@grai.io
      - DJANGO_SUPERUSER_PASSWORD=super_secret
      - DJANGO_SUPERUSER_WORKSPACE=Workspace1
      - SERVER_HOST=localhost
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - SECRET_KEY="This-Is-A-Test_key"
    entrypoint: /bin/sh
    command:
         - "-c"
         - "FRONTEND_URL=$$UFFIZZI_URL/ /start-celeryworker"
    deploy:
          resources:
            limits:
              memory: 2000M  
  celery_beat_worker:
    image: "${SERVER_IMAGE}"
    volumes:
      - ./grai-server/app/:/usr/src/app/
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=grai
      - DB_USER=grai
      - DB_PASSWORD=grai
      - DJANGO_SUPERUSER_USERNAME=null@grai.io
      - DJANGO_SUPERUSER_PASSWORD=super_secret
      - DJANGO_SUPERUSER_WORKSPACE=Workspace1
      - SERVER_HOST=localhost
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - SECRET_KEY="This-Is-A-Test_key"
    entrypoint: /bin/sh
    command:
         - "-c"
         - "FRONTEND_URL=$$UFFIZZI_URL/ /start-celerybeat"
    deploy:
          resources:
            limits:
              memory: 2000M        
